export const companies = [
  {
    id: "1",
    name: "Stripe",
    industry: "FinTech",
    stage: "Late Stage",
    location: "San Francisco",
    website: "https://stripe.com",
    founded: 2010,
    employees: 8000,
    funding: "$8.7B+",
    description:
      "Global payment processing infrastructure powering internet businesses.",
  },
  {
    id: "2",
    name: "Notion",
    industry: "Productivity SaaS",
    stage: "Growth",
    location: "San Francisco",
    website: "https://notion.so",
    founded: 2016,
    employees: 400,
    funding: "$335M",
    description:
      "All-in-one workspace for notes, docs, and team collaboration.",
  },
  {
    id: "3",
    name: "OpenAI",
    industry: "Artificial Intelligence",
    stage: "Late Stage",
    location: "San Francisco",
    website: "https://openai.com",
    founded: 2015,
    employees: 1500,
    funding: "$13B+",
    description:
      "AI research and deployment company building general-purpose AI systems.",
  },
  {
    id: "4",
    name: "SpaceX",
    industry: "Aerospace",
    stage: "Late Stage",
    location: "Hawthorne",
    website: "https://spacex.com",
    founded: 2002,
    employees: 12000,
    funding: "Private Funding",
    description:
      "Designs, manufactures, and launches advanced rockets and spacecraft.",
  },
  {
    id: "5",
    name: "Canva",
    industry: "Design Software",
    stage: "Growth",
    location: "Sydney",
    website: "https://canva.com",
    founded: 2013,
    employees: 3000,
    funding: "$570M+",
    description:
      "Online design platform simplifying graphic creation for everyone.",
  },
  {
    id: "6",
    name: "Snowflake",
    industry: "Cloud Data",
    stage: "Public",
    location: "Bozeman",
    website: "https://snowflake.com",
    founded: 2012,
    employees: 6000,
    funding: "IPO",
    description:
      "Cloud-based data warehousing platform enabling scalable analytics.",
  },
]